// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADIqRkxpdtNOkeNmJXuaGuGaoNFOCZ_UQ',
    appId: '1:492924908654:web:ae28a33412e4b7ea73a27f',
    messagingSenderId: '492924908654',
    projectId: 'kids-learning-eece2',
    authDomain: 'kids-learning-eece2.firebaseapp.com',
    storageBucket: 'kids-learning-eece2.firebasestorage.app',
    measurementId: 'G-91FC8QEM93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXt8B4hDHUSam_QnEjVid14FLuzWed3gc',
    appId: '1:492924908654:android:1b61b8fa4722a29773a27f',
    messagingSenderId: '492924908654',
    projectId: 'kids-learning-eece2',
    storageBucket: 'kids-learning-eece2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0xYXDPPIYe1uI14mcCtFx0Wvt53HsvnM',
    appId: '1:492924908654:ios:f7b72ba982e6daf273a27f',
    messagingSenderId: '492924908654',
    projectId: 'kids-learning-eece2',
    storageBucket: 'kids-learning-eece2.firebasestorage.app',
    iosBundleId: 'com.example.fluttertest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0xYXDPPIYe1uI14mcCtFx0Wvt53HsvnM',
    appId: '1:492924908654:ios:f7b72ba982e6daf273a27f',
    messagingSenderId: '492924908654',
    projectId: 'kids-learning-eece2',
    storageBucket: 'kids-learning-eece2.firebasestorage.app',
    iosBundleId: 'com.example.fluttertest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADIqRkxpdtNOkeNmJXuaGuGaoNFOCZ_UQ',
    appId: '1:492924908654:web:75573fe861f2492073a27f',
    messagingSenderId: '492924908654',
    projectId: 'kids-learning-eece2',
    authDomain: 'kids-learning-eece2.firebaseapp.com',
    storageBucket: 'kids-learning-eece2.firebasestorage.app',
    measurementId: 'G-VEEX8CE8FY',
  );
}
